version: "3"
services:
  #TCP: 24224
  fluentd:
    # user: fluent
    image: fluent/fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ./conf:/fluentd/etc
      - /volumes/fluentd:/logs:Z
