version: '3'
services:
  publisher:
    build: .
    environment:
      - MONGO_HOST=db
      - MONGO_DB=fastapi
      - RMQ_HOST=rabbitmq
      - RMQ_USERNAME=user
      - RMQ_PASSWORD=bitnami
      - message_queue_topic=publish_message_queue_topic


