version: 0.1
log:
  level: debug
  formatter: text
  fields:
    service: registry
    environment: staging
loglevel: debug
storage:
  s3:
    accesskey: MEDDLER
    secretkey: SUPERDUPERSECRET
    region: meddler
    regionendpoint: http://minio:9000
    # Make sure you've created the following bucket.
    bucket: docker
    encrypt: false
    # keyid: mykeyid
    secure: false
    skipverify: true
    v4auth: false
    chunksize: 5242880
    rootdirectory: /
  delete:
    enabled: true
  maintenance:
    uploadpurging:
      enabled: true
      age: 168h
      interval: 24h
      dryrun: false
    readonly:
      enabled: false
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]

  # tls:
      # certificate: /certs/domain.crt
      # key: /certs/domain.key