version: "3"
services:
  #TCP: 24224
  fluentd:
    extends:
      file: ./fluentd/docker-compose.yaml
      service: fluentd
    volumes:
      - /volumes/fluentd:/logs:Z
    restart: always

  #TCP: 24224
  minio:
    extends:
      file: ./minio/docker-compose.yml
      service: minio
    volumes:
      - /volumes/minio/data:/data
    environment:
      MINIO_ACCESS_KEY: MEDDLER
      MINIO_SECRET_KEY: SUPERDUPERSECRET
      MINIO_REGION_NAME: meddler
    restart: always

  # #8082
  log_reader:
    extends:
      file: ./log_reader/docker-compose.yaml
      service: log_reader
    volumes:
      - /volumes/fluentd:/log:ro
    restart: always

  rabbitmq:
    extends:
      file: ./rabbitmq/docker-compose.yml
      service: rabbitmq
    volumes:
      - /volumes/rmq:/bitnami:Z
    restart: always

  registry:
    extends:
      file: ./registry/docker-compose.yaml
      service: registry
    restart: always

  db:
    extends:
      file: ./db/docker-compose.yaml
      service: db
    volumes:
      - /volumes/mongodb:/data/db
    restart: always

  # Tools on top of watchdog bootstrapper
  tool_builder:
    extends:
      file: ./tool_builder/docker-compose.yml
      service: tool_builder
    restart: always
