version: "3"
services:
  #TCP: 24224
  fluentd:
    extends:
      file: ./fluentd/docker-compose.yaml
      service: fluentd
    volumes:
      - /volumes/fluentd:/logs:Z


  #TCP: 24224
  minio:
    extends:
      file: ./minio/docker-compose.yml
      service: minio
    volumes:
      - /volumes/minio/data:/data
    environment:
      MINIO_ACCESS_KEY: MEDDLER
      MINIO_SECRET_KEY: SUPERDUPERSECRET
      MINIO_REGION_NAME: meddler

  # #8082
  log_reader:
    extends:
      file: ./log_reader/docker-compose.yaml
      service: log_reader
    volumes:
      - /volumes/build_logs:/log:ro



  rabbitmq:
    extends:
      file: ./rabbitmq/docker-compose.yml
      service: rabbitmq
    volumes:
      - /volumes/rmq:/bitnami:Z

  registry:
    extends:
      file: ./registry/docker-compose.yaml
      service: registry
