version: '3'
services:
  db:
    image: mongo
    command:  ["--replSet", "rs0", "--bind_ip_all"] #  --config /etc/mongo/mongod.conf
    volumes:
      - ./mongo.conf:/etc/mongo/mongod.conf
    ports:
      - 27017:27017
    expose:
      - 27017
