version: '2'

services:
  minio:
    image: 'minio/minio'
    command: server /data --console-address ":9001"
    volumes:
      - ./data:/data
    environment:
      MINIO_ACCESS_KEY: MEDDLER
      MINIO_SECRET_KEY: SUPERDUPERSECRET
    ports:
      - '9000:9000'
      - '9001:9001'
    expose:
      - 9000
      - 9001

